import React,{useEffect,useRef,useState} from 'react';
import Editor from '@monaco-editor/react';
import {X,Plus,Copy,Download,Upload,Trash2,RotateCcw,Search,Pencil,Check,LoaderCircle,ArrowLeft,RefreshCw} from 'lucide-react';
const bundleOf=problem=>({format:'tensor-dojo-bank',version:1,problems:[problem]});
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function BankManager({token,onClose,onChanged}){
 const [bank,setBank]=useState(null),[query,setQuery]=useState(''),[selected,setSelected]=useState([]),[view,setView]=useState('list'),[edit,setEdit]=useState(null),[editRevision,setEditRevision]=useState(null),[editingId,setEditingId]=useState(null),[tests,setTests]=useState('[]'),[section,setSection]=useState('info'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[confirmation,setConfirmation]=useState(null),[importText,setImportText]=useState(''),[filename,setFilename]=useState(''),[overwrite,setOverwrite]=useState(false),[preview,setPreview]=useState(null);
 const [forbiddenText,setForbiddenText]=useState(''),[constantsText,setConstantsText]=useState('');
 const tokenRef=useRef(token),busyRef=useRef(false),fileRef=useRef(null),dialogRef=useRef(null);
 async function request(path,method='GET',body){const response=await fetch('/api/bank'+path,{method,headers:{'Content-Type':'application/json','X-Dojo-Token':tokenRef.current},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败');return data;}
 async function load(){const h=await fetch('/api/health').then(r=>r.json());tokenRef.current=h.token;const b=await request('');setBank(b);setSelected(s=>s.filter(id=>b.problems.some(p=>p.id===id)));return b;}
 async function perform(fn){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e.message)}finally{busyRef.current=false;setBusy(false)}}
 useEffect(()=>{perform(load);dialogRef.current?.focus()},[]);
 useEffect(()=>{function guard(e){if(dirty){e.preventDefault();e.returnValue=''}}window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
 function exit(){if(busyRef.current)return;if(dirty)setConfirmation({kind:'leave',title:'放弃未保存的修改？',body:'当前修改尚未保存到题库。',action:onClose});else onClose()}
 function back(){if(dirty)setConfirmation({kind:'leave',title:'放弃未保存的修改？',body:'当前修改尚未保存到题库。',action:()=>{setView('list');setDirty(false);setError('')}});else{setView('list');setError('');setMessage('')}}
 function keys(e){e.stopPropagation();if(e.key==='Escape'){e.preventDefault();if(confirmation)setConfirmation(null);else exit()}if(e.key==='Tab'){const focusRoot=dialogRef.current.querySelector('[role=alertdialog]')||dialogRef.current;const elements=[...focusRoot.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]')].filter(x=>x.getClientRects().length);const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}
 function patch(key,value){setEdit(p=>({...p,[key]:value}));setDirty(true);setMessage('')}
 function openEditor(p,revision,id=null){setEdit(p);setForbiddenText((p.forbidden||[]).join(','));setConstantsText((p.constant_indices||[]).join(','));setTests(JSON.stringify(p.tests,null,2));setEditingId(id);setEditRevision(revision);setSection('info');setView('edit');setDirty(false);setError('');setMessage('')}
 async function startEdit(id,copy=false){await perform(async()=>{const response=await request('/problems/'+encodeURIComponent(id));const p=response.problem;if(copy){let base=id.slice(0,50)+'-copy',next=base,n=2;while(bank.problems.some(row=>row.id===next)||bank.deleted.includes(next))next=base+'-'+n++;p.id=next;p.title+='（副本）'}openEditor(p,response.revision,copy?null:id)})}
 async function create(){await perform(async()=>{const sample=await request('/example');const p=sample.problems[0];p.id='';p.title='L1 归一化练习';openEditor(p,bank.revision);setMessage('已填入可运行的 L1 示例；请设置唯一 ID，并按需要修改内容。')})}
 function problemData(){if(!edit.id.trim()||!edit.title.trim())throw new Error('请填写题目 ID 和标题');let parsed;try{parsed=JSON.parse(tests)}catch{throw new Error('测试用例不是合法 JSON，请在“测试数据”中修正。')}return {...edit,tests:parsed,forbidden:forbiddenText.split(',').map(s=>s.trim()).filter(Boolean),constant_indices:constantsText.split(',').filter(s=>s.trim()).map(Number)};}
 async function save(validateOnly=false){await perform(async()=>{const p=problemData();if(validateOnly){const r=await request('/validate','POST',{bundle:bundleOf(p)});setMessage(`校验通过：${r.validated} 道题，参考实现与测试一致。`);return}await request(editingId?'/problems/'+encodeURIComponent(editingId):'/problems',editingId?'PUT':'POST',{problem:p,expected_revision:editRevision});setDirty(false);setView('list');await load();await onChanged();setMessage(editingId?'题目已更新。':'题目已创建。')})}
 async function remove(id){await perform(async()=>{await request('/problems/'+encodeURIComponent(id),'DELETE',{expected_revision:bank.revision});setConfirmation(null);await load();await onChanged();setMessage('题目已删除，可在“已删除题目”中恢复。')})}
 async function restore(id){await perform(async()=>{await request('/problems/'+encodeURIComponent(id)+'/restore','POST',{expected_revision:bank.revision});await load();await onChanged();setMessage('题目已恢复。')})}
 async function exportRows(ids){await perform(async()=>{const value=await request('/export'+(ids?'?ids='+encodeURIComponent(ids.join(',')):''));download(ids?.length===1?ids[0]+'.json':'tensor-dojo-bank.json',value);setMessage(`已导出 ${value.problems.length} 道题目。`)})}
 function changeImport(text){setImportText(text);setDirty(!!text);setPreview(null);setError('');setMessage('')}
 async function readFile(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;await perform(async()=>{if(file.size>8*1024*1024)throw new Error('文件不能超过 8 MiB');changeImport(await file.text());setFilename(file.name)})}
 async function importBank(commit=false){await perform(async()=>{let bundle;try{bundle=JSON.parse(importText)}catch{throw new Error('导入内容不是合法 JSON')}if(commit&&!preview)throw new Error('请先完成导入预检');const revision=commit?preview.revision:bank.revision;const r=await request('/import','POST',{bundle,expected_revision:revision,overwrite,dry_run:!commit});if(!commit){setPreview(r);setMessage('预检通过，核对下方题目与覆盖列表后点击“确认导入”。')}else{setDirty(false);setView('list');setImportText('');setPreview(null);await load();await onChanged();setMessage(`已导入 ${r.validated} 道题目。`)}})}
 const filtered=bank?.problems.filter(p=>(p.title+' '+p.id+' '+p.category).toLowerCase().includes(query.toLowerCase()))||[];
 const fields=[['id','题目 ID'],['title','标题'],['category','分类'],['signature','函数参数（不含 def solve）'],['source','参考链接']];
 return <div className="bank-backdrop"><section className="bank-manager" role="dialog" aria-modal="true" aria-label="题库管理" tabIndex={-1} ref={dialogRef} onKeyDown={keys}>
  <header className="bank-header"><div><span className="eyebrow">QUESTION BANK</span><h2>题库管理 <small>{bank?.problems.length??'—'} 道题目</small></h2></div><button className="icon" onClick={exit} aria-label="关闭题库管理" disabled={busy}><X size={23}/></button></header>
  <div className="bank-navigation">{view!=='list'?<button className="secondary" onClick={back} disabled={busy}><ArrowLeft size={15}/>返回列表</button>:<span>管理题目与可移植 JSON 题库</span>}<div><span>版本 {bank?.revision??'—'}</span><button className="secondary" disabled={busy} onClick={()=>perform(async()=>{await load();setPreview(null);setMessage('已刷新列表。未保存的编辑保留原版本；发生冲突时请返回列表重新打开题目。')})}><RefreshCw size={14}/>刷新列表</button></div></div>
  {error&&<div className="bank-error" role="alert"><strong>操作未完成</strong><pre>{error}</pre></div>}{message&&<div className="bank-message" role="status"><Check size={16}/>{message}</div>}
  {busy&&<div className="bank-working" role="status"><LoaderCircle size={15} className="spin"/>正在处理，请稍候。代码校验最多需要 40 秒。</div>}
  <div className="bank-body" aria-busy={busy}>
   {view==='list'&&<><div className="bank-actions"><button className="primary" onClick={create} disabled={busy||!bank}><Plus size={16}/>新建题目</button><button className="secondary" disabled={busy||!bank} onClick={()=>{setView('import');setImportText('');setFilename('');setPreview(null);setOverwrite(false);setError('');setMessage('')}}><Upload size={16}/>导入 JSON</button><button className="secondary" disabled={busy||!bank?.problems.length} onClick={()=>exportRows()}><Download size={16}/>导出全部</button><button className="secondary" disabled={busy||!selected.length} onClick={()=>exportRows(selected)}>导出选中 ({selected.length})</button></div><label className="bank-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、ID 或分类" aria-label="搜索管理题库"/></label>
    <div className="bank-table-wrap"><table className="bank-table"><thead><tr><th><input type="checkbox" aria-label="选中当前筛选结果" checked={filtered.length>0&&filtered.every(p=>selected.includes(p.id))} onChange={e=>setSelected(s=>e.target.checked?[...new Set([...s,...filtered.map(p=>p.id)])]:s.filter(id=>!filtered.some(p=>p.id===id)))}/></th><th>题目</th><th>分类</th><th>来源</th><th>操作</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><input type="checkbox" aria-label={'选择 '+p.title} checked={selected.includes(p.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(id=>id!==p.id))}/></td><td><strong>{p.title}</strong><code>{p.id}</code></td><td>{p.category}</td><td><span className="bank-source">{p.customized?'自定义 / 已修改':'内置'}</span></td><td><div className="bank-row-actions"><button onClick={()=>startEdit(p.id)} disabled={busy} aria-label={'编辑 '+p.title}><Pencil size={14}/>编辑</button><button onClick={()=>startEdit(p.id,true)} disabled={busy} aria-label={'复制 '+p.title}><Copy size={14}/>复制</button><button onClick={()=>exportRows([p.id])} disabled={busy} aria-label={'导出 '+p.title}><Download size={14}/>导出</button><button className="danger" disabled={busy} aria-label={'删除 '+p.title} onClick={()=>setConfirmation({kind:'delete',id:p.id,title:'删除这道题目？',body:`“${p.title}”将从练习题库隐藏。成绩和草稿保留，可在下方恢复。`})}><Trash2 size={14}/>删除</button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state">{bank?'没有匹配的题目。':'正在加载题库…'}</div>}</div>
    <details className="bank-deleted"><summary>已删除题目 ({bank?.deleted.length??0})</summary>{bank?.deleted.length?bank.deleted.map(id=><div key={id}><code>{id}</code><button className="secondary" disabled={busy} onClick={()=>restore(id)}><RotateCcw size={14}/>恢复题目</button></div>):<p>没有已删除的题目。</p>}</details></>}
   {view==='edit'&&edit&&<><div className="bank-edit-title"><h3>{editingId?'编辑题目':'新建 / 复制题目'}</h3><span>{dirty?'有未保存的修改':'尚未提交新的修改'}</span></div><nav className="bank-edit-tabs" aria-label="题目编辑步骤">{[['info','基本信息'],['solution','参考实现'],['starter','练习模板'],['tests','测试数据'],['rules','判题规则']].map(([key,label])=><button key={key} className={section===key?'selected':''} onClick={()=>setSection(key)}>{label}</button>)}</nav>
    <fieldset disabled={busy} className="bank-fields">{section==='info'&&<div className="bank-form">{fields.map(([key,label])=><label key={key}>{label}<input value={edit[key]??''} readOnly={key==='id'&&!!editingId} onChange={e=>patch(key,e.target.value)} placeholder={key==='id'?'例如 my-l1-normalize':''}/></label>)}<label>难度<select value={edit.difficulty} onChange={e=>patch('difficulty',e.target.value)}>{['入门','基础','进阶','挑战'].map(x=><option key={x}>{x}</option>)}</select></label><label>建议分钟数<input type="number" min="1" max="600" value={edit.minutes} onChange={e=>patch('minutes',e.target.value===''?'':Number(e.target.value))}/></label><label className="wide">题目描述<textarea rows={5} value={edit.description} onChange={e=>patch('description',e.target.value)}/></label><label className="wide">核心公式<textarea rows={3} value={edit.formula??''} onChange={e=>patch('formula',e.target.value)}/></label><label className="wide">提示（每行一条）<textarea rows={3} value={(edit.hints||[]).join('\n')} onChange={e=>patch('hints',e.target.value.split('\n'))}/></label></div>}
    {['solution','starter','tests'].includes(section)&&<><p className="bank-help">{section==='solution'?'定义顶层 solve 函数。保存时将执行参考实现，并与所有测试期望值核对。':section==='starter'?'留空可自动生成练习模板；自定义代码需包含 solve。缺少 __main__ 时自动生成快速运行入口。':'JSON 数组；每项包含 name、args、expected。张量使用 type、dtype、shape、data 编码，data 为扁平数组。'}</p><div className="bank-code"><Editor key={section} language={section==='tests'?'plaintext':'python'} theme="dojo" value={section==='tests'?tests:edit[section]||''} onChange={v=>{if(section==='tests'){setTests(v||'');setDirty(true)}else patch(section,v||'')}} options={{readOnly:busy,minimap:{enabled:false},fontSize:14,automaticLayout:true,wordWrap:'on',scrollBeyondLastLine:false,tabSize:4}}/></div></>}
    {section==='rules'&&<div className="bank-rule-form"><label><input type="checkbox" checked={edit.inference_only||false} onChange={e=>patch('inference_only',e.target.checked)}/>仅检查数值，不检查梯度</label><label><input type="checkbox" checked={edit.immutable_inputs||false} onChange={e=>patch('immutable_inputs',e.target.checked)}/>禁止原地修改输入</label><label>禁止调用的函数名（逗号分隔）<input value={forbiddenText} onChange={e=>{setForbiddenText(e.target.value);setDirty(true)}}/></label><label>不启用梯度的参数下标（逗号分隔，从 0 开始）<input value={constantsText} onChange={e=>{setConstantsText(e.target.value);setDirty(true)}}/></label><p className="bank-help">若需要检查旧策略参数是否正确 detach，请保留其梯度检查，在参考实现内停止梯度。</p></div>}
    </fieldset><footer className="bank-form-footer"><span>保存前会自动校验；现有练习草稿不会被替换。</span><button className="secondary" disabled={busy} onClick={()=>save(true)}>仅校验</button><button className="primary" disabled={busy} onClick={()=>save()}>校验并保存</button></footer></>}
   {view==='import'&&<><h3>导入 JSON 题库</h3><p className="bank-help">选择导出的题库文件，或粘贴内容。导入包含参考 Python 代码，请使用可信文件。</p><div className="bank-actions"><input ref={fileRef} type="file" accept=".json,application/json" onChange={readFile} hidden/><button className="secondary" disabled={busy} onClick={()=>fileRef.current.click()}><Upload size={15}/>选择 JSON 文件</button><span>{filename||'未选择文件，可直接粘贴 JSON'}</span><button className="secondary" disabled={busy} onClick={()=>perform(async()=>download('question-bank-example.json',await request('/example')))}>下载格式示例</button></div><label className="bank-import-label">题库 JSON<textarea rows={12} value={importText} disabled={busy} onChange={e=>changeImport(e.target.value)} spellCheck={false} placeholder={'{"format":"tensor-dojo-bank","version":1,"problems":[…]}'}/></label><label className="bank-check"><input type="checkbox" checked={overwrite} disabled={busy} onChange={e=>{setOverwrite(e.target.checked);setPreview(null)}}/>允许覆盖同 ID 题目（默认保留原题并报告冲突）</label>{preview&&<div className="bank-preview"><h3>预检通过 · {preview.validated} 道题</h3><p>将导入：{preview.ids.join('、')}</p><p>将覆盖：{preview.overwritten.length?preview.overwritten.join('、'):'无'}</p><small>题库版本 {preview.revision}；此时尚未写入。</small></div>}<footer className="bank-form-footer"><button className="secondary" disabled={busy||!importText.trim()} onClick={()=>importBank(false)}>预检导入</button><button className="primary" disabled={busy||!preview} onClick={()=>importBank(true)}>确认导入{preview?` ${preview.validated} 道题`:''}</button></footer></>}
  </div>
  {confirmation&&<div className="bank-confirm-backdrop"><div role="alertdialog" aria-modal="true" aria-label={confirmation.title} className="bank-confirm"><h3>{confirmation.title}</h3><p>{confirmation.body}</p><div><button className="secondary" autoFocus disabled={busy} onClick={()=>setConfirmation(null)}>取消</button><button className="primary" disabled={busy} onClick={()=>{if(confirmation.kind==='delete')remove(confirmation.id);else{const action=confirmation.action;setConfirmation(null);action()}}}>{confirmation.kind==='delete'?'确认删除':'放弃修改'}</button></div></div></div>}
 </section></div>
}
