import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import Editor, {loader} from '@monaco-editor/react';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
import 'monaco-editor/esm/vs/basic-languages/python/python.contribution';
import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
import {ArrowUpRight, BookOpen, Check, CheckCheck, ChevronRight, Clock3, Code2, Copy, Cpu, FileCode2, FlaskConical, History, Keyboard, Lightbulb, ListFilter, LoaderCircle, Menu, Play, RotateCcw, Search, Send, Terminal, Trophy, X, XCircle} from 'lucide-react';
import './style.css';
import BankManager from './BankManager';
self.MonacoEnvironment={getWorker:()=>new EditorWorker()};
loader.config({monaco});
const defaultCategories=['全部题目','注意力机制','损失函数','强化学习','评价指标','Normalization','KV Cache','基础算子'];
const icons={'注意力机制':Cpu,'损失函数':FlaskConical,'强化学习':Trophy,'基础算子':Code2,'评价指标':CheckCheck,'Normalization':ListFilter,'KV Cache':History};
const fontFamilies=[
 {label:'JetBrains Mono',value:"'JetBrains Mono','DejaVu Sans Mono',monospace"},
 {label:'Fira Code',value:"'Fira Code','JetBrains Mono',monospace"},
 {label:'Cascadia Code',value:"'Cascadia Code','Consolas',monospace"},
 {label:'Source Code Pro',value:"'Source Code Pro','JetBrains Mono',monospace"},
 {label:'Consolas',value:"'Consolas',monospace"},
 {label:'Menlo',value:"'Menlo','Monaco',monospace"},
 {label:'Monospace',value:'monospace'}
];
async function api(path,options){const response=await fetch('/api'+path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
function stored(key,fallback){try{return localStorage.getItem(key)??fallback;}catch{return fallback;}}
function App(){
 const [showManager,setShowManager]=useState(false),[bankVersion,setBankVersion]=useState(0);
 async function refreshBank(){const [p,h,s]=await Promise.all([api('/problems'),api('/health'),api('/progress')]);setProblems(p);setEnv(h);setProgress(s);if(!p.some(row=>row.id===activeRef.current)){if(p.length)setActive(p[0].id);else{setProblem(null);setError('')}}else setBankVersion(v=>v+1);}

 const [problems,setProblems]=useState([]),[active,setActive]=useState(stored('dojo.active','self-attention')),[problem,setProblem]=useState(null),[category,setCategory]=useState('全部题目'),[query,setQuery]=useState(''),[progress,setProgress]=useState({}),[env,setEnv]=useState(null),[error,setError]=useState('');
 const [code,setCode]=useState(''),[tab,setTab]=useState('description'),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[runningMode,setRunningMode]=useState(''),[history,setHistory]=useState([]),[solution,setSolution]=useState(null),[showSolution,setShowSolution]=useState(false),[showReset,setShowReset]=useState(false),[sidebar,setSidebar]=useState(false),[toast,setToast]=useState(''),[fontSize,setFontSize]=useState(Number(stored('dojo.font','14'))),[fontFamily,setFontFamily]=useState(stored('dojo.fontFamily',"'Consolas',monospace")),[onlyUnsolved,setOnlyUnsolved]=useState(false),[seconds,setSeconds]=useState(0),[saveError,setSaveError]=useState(false);
 useEffect(()=>{function escape(e){if(e.key==='Escape'){setShowSolution(false);setShowReset(false);setSidebar(false)}}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 const activeRef=useRef(active),editorRef=useRef(null),runRef=useRef(null),busyRef=useRef(false);
 const notify=(message)=>setToast(message);
 useEffect(()=>{if(!env)return;const kind={'function':monaco.languages.CompletionItemKind.Function,'class':monaco.languages.CompletionItemKind.Class,'module':monaco.languages.CompletionItemKind.Module,'instance':monaco.languages.CompletionItemKind.Field,'keyword':monaco.languages.CompletionItemKind.Keyword,'statement':monaco.languages.CompletionItemKind.Keyword,'param':monaco.languages.CompletionItemKind.Variable,'property':monaco.languages.CompletionItemKind.Property};const provider=monaco.languages.registerCompletionItemProvider('python',{triggerCharacters:['.'],async provideCompletionItems(model,position){const word=model.getWordUntilPosition(position);const range={startLineNumber:position.lineNumber,endLineNumber:position.lineNumber,startColumn:word.startColumn,endColumn:word.endColumn};try{const response=await fetch('/api/complete',{method:'POST',headers:{'Content-Type':'application/json','X-Dojo-Token':env.token},body:JSON.stringify({code:model.getValue(),line:position.lineNumber,column:position.column})});const data=await response.json();if(!response.ok||!data.items?.length)return {suggestions:[]};return {suggestions:data.items.map(item=>({label:item.label,kind:kind[item.type]||monaco.languages.CompletionItemKind.Text,detail:item.detail,insertText:item.insertText||item.label,documentation:item.documentation||undefined,range}))}}catch{return {suggestions:[]}}}});return ()=>provider.dispose()},[env]);
 useEffect(()=>{Promise.all([api('/problems'),api('/health'),api('/progress')]).then(([p,e,s])=>{setProblems(p);if(p.length&&!p.some(row=>row.id===activeRef.current))setActive(p[0].id);setEnv(e);setProgress(s);}).catch(e=>setError('无法连接本地判题服务：'+e.message));},[]);
 useEffect(()=>{activeRef.current=active;let stale=false;setProblem(null);setResult(null);setTab('description');setShowSolution(false);setSolution(null);setSeconds(0);try{localStorage.setItem('dojo.active',active);}catch{}
 api('/problems/'+active).then(p=>{if(!stale){setError('');setProblem(p);setCode(stored('dojo.code.'+active,p.starter));}}).catch(e=>{if(!stale)setError(e.message)});
 api('/problems/'+active+'/history').then(h=>{if(!stale)setHistory(h)}).catch(()=>{});return()=>{stale=true;};},[active,bankVersion]);
 useEffect(()=>{let t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[active]);
 useEffect(()=>{if(toast){let t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{function handler(e){if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();runRef.current?.(e.shiftKey?'submit':'run')}}window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
 function updateCode(value){setCode(value??'');try{localStorage.setItem('dojo.code.'+active,value??'');setSaveError(false)}catch{setSaveError(true)}}
 async function run(mode){if(busyRef.current||!env||!problem)return;busyRef.current=true;setBusy(true);setRunningMode(mode);setResult(null);const id=active;let submitted=editorRef.current?.getValue()??code;
 if(mode==='demo'&&!submitted.includes('__main__'))submitted+=problem.runner;
 try{const r=await api('/judge',{method:'POST',headers:{'Content-Type':'application/json','X-Dojo-Token':env.token},body:JSON.stringify({problem_id:id,code:submitted,mode})});if(activeRef.current===id)setResult({...r,mode});if(mode==='submit'){setProgress(await api('/progress'));const h=await api('/problems/'+id+'/history');if(activeRef.current===id)setHistory(h);}}
 catch(e){if(activeRef.current===id)setResult({status:'error',error:e.message,cases:[]})}finally{busyRef.current=false;setBusy(false);setRunningMode('')}}
 runRef.current=run;
 function appendRunner(){if(code.includes('__main__'))return notify('当前代码已有运行入口');updateCode(code+problem.runner);notify('已追加运行入口，原有实现保留')}
 function downloadTemplate(){const url=URL.createObjectURL(new Blob([problem.starter],{type:'text/x-python;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=problem.id+'.py';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function viewSolution(){try{const s=await api('/problems/'+active+'/solution');setSolution(s.code);setShowSolution(true)}catch(e){notify(e.message)}}
 const categories=['全部题目',...new Set([...defaultCategories.slice(1),...problems.map(p=>p.category)])];
 const filtered=problems.filter(p=>(category==='全部题目'||p.category===category)&&(!onlyUnsolved||!progress[p.id]?.solved)&&(p.title+' '+p.id).toLowerCase().includes(query.toLowerCase()));
 const solved=Object.values(progress).filter(p=>p.solved&&problems.some(row=>row.id===p.problem_id)).length;
 const index=problems.findIndex(p=>p.id===active);
 const isSolved=progress[active]?.solved;
 const iconProps={size:16,strokeWidth:1.7};
 return <div className="app">
  <header className="topbar"><div className="brand"><button className="icon mobile-menu" onClick={()=>setSidebar(!sidebar)} aria-label="打开题库"><Menu size={20}/></button><span className="brandmark">T<span>_</span></span><strong>TENSOR<span>DOJO</span></strong><span className="brand-caption">手撕代码训练场</span></div><div className="topright"><button className="secondary bank-open" onClick={()=>setShowManager(true)}>题库管理</button><span className={'runtime '+(env?'online':'')}>{env?<Cpu size={14}/>:<LoaderCircle size={14}/>} {env?'本地 PyTorch '+env.torch.split('+')[0]:'连接本地环境'}</span><span className="avatar">YOU</span></div></header>
  <div className="workspace">
   <aside className={'sidebar '+(sidebar?'open':'')}>
    <div className="sidebar-top"><div className="eyebrow">YOUR PRACTICE SPACE</div><h2>从理解，到手写。</h2><p>把大模型的核心，写进肌肉记忆。</p></div>
    <div className="progress-card"><div><span>训练进度</span><strong>{solved}<small> / {problems.length}</small></strong></div><div className="progress-track"><i style={{width:problems.length?`${solved/problems.length*100}%`:'0%'}}/></div><p>{solved===0?'从一道题开始，建立你的第一块积木。':`已攻克 ${solved} 道，继续保持。`}</p></div>
    <nav className="categories" aria-label="题目分类">{categories.map(c=>{const Icon=icons[c]||BookOpen;return <button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}><Icon {...iconProps}/><span>{c}</span><small>{c==='全部题目'?problems.length:problems.filter(p=>p.category===c).length}</small></button>})}</nav>
    <div className="listheading"><span>题目列表</span><button className={'icon '+(onlyUnsolved?'toggled':'')} onClick={()=>setOnlyUnsolved(!onlyUnsolved)} title="只看未完成" aria-label="只看未完成" aria-pressed={onlyUnsolved}><ListFilter size={16}/></button></div>
    <label className="search"><Search size={15}/><input placeholder="搜索题目…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="搜索题目"/><kbd>⌕</kbd></label>
    <div className="problem-list">{filtered.map(p=><button key={p.id} onClick={()=>{setActive(p.id);setSidebar(false)}} className={'problem-item '+(active===p.id?'active':'')}><span className={'problem-status '+(progress[p.id]?.solved?'done':'')}>{progress[p.id]?.solved?<Check size={13}/>:String(problems.indexOf(p)+1).padStart(2,'0')}</span><span><strong>{p.title}</strong><small><i className={'level '+p.difficulty}/>{p.difficulty}<span>·</span>{p.minutes} min</small></span>{active===p.id&&<ChevronRight size={15}/>}</button>)}{!filtered.length&&<p className="empty-list">没有匹配的题目</p>}</div>
    <div className="sidebar-footer"><span className="local-dot"/>草稿保存在此浏览器 <span>v1.0</span></div>
   </aside>
   <main>
    <div className="breadcrumb"><span>练习工作台</span><ChevronRight size={13}/><span>{problem?.category||'加载中'}</span><ChevronRight size={13}/><strong>{problem?.id.toUpperCase()}</strong><div className="session"><Clock3 size={14}/>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</div></div>
    {error&&<div className="error-banner">{error}<button onClick={()=>location.reload()}>重新连接</button></div>}
    <div className="split">
     <section className="problem-panel">
      <div className="panel-tabs"><button className={tab==='description'?'current':''} onClick={()=>setTab('description')}><BookOpen {...iconProps}/>题目描述</button><button className={tab==='hints'?'current':''} onClick={()=>setTab('hints')}><Lightbulb {...iconProps}/>思路提示</button><button className={tab==='template'?'current':''} onClick={()=>setTab('template')}><FileCode2 {...iconProps}/>运行模板</button><button className={tab==='history'?'current':''} onClick={()=>setTab('history')}><History {...iconProps}/>提交记录 <span className="tab-count">{history.length}</span></button></div>
      <div className="problem-content">{problem?<>
       <div className="problem-kicker">CHALLENGE {String(index+1).padStart(2,'0')} <span>{isSolved?<><CheckCheck size={14}/>已通过</>:'待挑战'}</span></div>
       <h1>{problem.title}</h1><div className="tags"><span className={'difficulty '+problem.difficulty}>{problem.difficulty}</span><span>{problem.category}</span><span><Clock3 size={13}/>{problem.minutes} 分钟</span><span>PyTorch</span></div>
       {tab==='description'&&<><h3>实现目标</h3><p className="description">{problem.description}</p><h3>核心公式</h3><pre className="formula">{problem.formula}</pre><h3>函数签名</h3><pre className="signature">solve({problem.signature})</pre><h3>输入样例 <span className="subtle">形状与数据预览</span></h3>{problem.examples.map((ex,i)=><details className="example" key={i} open={i===0}><summary><span>0{i+1}</span>{ex.name}<ChevronRight size={14}/></summary><div>{ex.inputs.map((v,j)=><div className="input-row" key={j}><code>{problem.signature.split(',')[j]?.split('=')[0].trim()}</code><span>{v?.shape?`[${v.shape.join(', ')}] · ${v.dtype.replace('torch.','')}`:String(v)}</span>{v?.preview&&<pre>{v.preview}</pre>}</div>)}<div className="input-row"><code>输出预览</code><pre>{ex.output}</pre></div></div></details>)}<div className="judge-note"><FlaskConical size={17}/><p>样例运行检查前 2 组；提交检查全部 {problem.totalTests??problem.testCount*3} 组数据，包括随机回归{problem.inference_only?'；本题不要求梯度':'与梯度一致性'}。误差容限：rtol 1e−5 / atol 1e−7。</p></div><a className="paper-link" href={problem.source} target="_blank" rel="noreferrer">阅读原始论文 / 官方文档 <ArrowUpRight size={14}/></a></>}
       {tab==='template'&&<div className="template-panel"><p className="description">保存为 .py 后用本地 Python 直接运行。模板包含示例输入、调用入口与期望输出，只需补全 solve。页面的“运行模板”执行当前编辑器代码，不计入成绩。</p><div className="template-actions"><button className="secondary" onClick={downloadTemplate}>下载 .py</button><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(problem.starter);notify('模板已复制')}catch{notify('复制失败，请下载模板')}}}><Copy size={14}/>复制模板</button><button className="secondary" onClick={appendRunner}>补充运行入口</button></div><pre className="template-code">{problem.starter}</pre></div>}
       {tab==='hints'&&<><p className="description">先尝试独立推导，再逐条展开提示。</p>{problem.hints.map((hint,i)=><details className="hint" key={hint}><summary><Lightbulb size={16}/>提示 {i+1}<ChevronRight size={14}/></summary><p>{hint}</p></details>)}<div className="solution-card"><Code2 size={22}/><h3>对照参考实现</h3><p>卡住时可以对照实现，理解后再从空白写一遍。</p><button className="secondary" onClick={viewSolution}>查看参考实现<ArrowUpRight size={14}/></button></div></>}
       {tab==='history'&&<div className="history-list">{history.length?history.map(h=><details key={h.id} className="history-item"><summary><span className={'verdict '+h.status}>{h.status==='accepted'?<Check size={16}/>:<XCircle size={16}/>}</span><span><strong>{h.status==='accepted'?'通过':h.status==='timeout'?'运行超时':'未通过'}</strong><small>{new Date(h.created_at.replace(' ','T')+'Z').toLocaleString('zh-CN')}</small></span><span>{h.result.passed??0}/{h.result.total??0}</span><ChevronRight size={14}/></summary><pre>{h.code}</pre><button className="secondary" onClick={()=>{updateCode(h.code);notify('已恢复该次提交的代码')}}>恢复到编辑器</button>{h.result.error&&<pre>{h.result.error}</pre>}</details>):<div className="empty-state"><History size={28}/><h3>还没有提交记录</h3><p>提交判题后，代码和结果会保存在本地。</p></div>}</div>}
      </>:env&&problems.length===0?<div className="empty-state"><BookOpen size={28}/><h3>题库为空</h3><p>通过题库管理接口导入题目后刷新页面。</p></div>:<div className="loading"><LoaderCircle className="spin"/>正在加载题目…</div>}</div>
      <footer className="problem-footer"><span>{index+1} / {problems.length} 题</span><button disabled={index<=0} onClick={()=>setActive(problems[index-1].id)}>上一题</button><button disabled={index>=problems.length-1||index<0} onClick={()=>setActive(problems[index+1].id)}>下一题 <ChevronRight size={14}/></button></footer>
     </section>
     <section className="coding-panel">
      <div className="editor-toolbar"><span><FileCode2 size={16}/>solution.py<span className="file-dot"/></span><div><span>Python 3</span><select className="editor-font-select" style={{maxWidth:132}} aria-label="编辑器字体" value={fontFamily} onChange={e=>{setFontFamily(e.target.value);try{localStorage.setItem('dojo.fontFamily',e.target.value)}catch{}}}>{fontFamilies.map(f=><option key={f.label} value={f.value}>{f.label}</option>)}</select><select aria-label="编辑器字号" value={fontSize} onChange={e=>{setFontSize(Number(e.target.value));try{localStorage.setItem('dojo.font',e.target.value)}catch{}}}>{[12,14,16,18,20].map(n=><option key={n} value={n}>{n}px</option>)}</select><button className="icon" title="重置代码" aria-label="重置代码" onClick={()=>setShowReset(true)} disabled={!problem}><RotateCcw size={15}/></button></div></div>
      <div className="editor"><Editor key={active} language="python" theme="vs-dark" value={code} onChange={updateCode} loading={<div className="loading">正在加载本地编辑器…</div>} beforeMount={m=>m.editor.defineTheme('dojo',{base:'vs-dark',inherit:true,rules:[{token:'comment',foreground:'687887'},{token:'keyword',foreground:'C1A6F6'},{token:'string',foreground:'BBD797'},{token:'number',foreground:'E9B986'}],colors:{'editor.background':'#151a22','editorLineNumber.foreground':'#4d5764','editorLineNumber.activeForeground':'#c7f568','editor.lineHighlightBackground':'#1b222c','editor.selectionBackground':'#3a4855'}})} onMount={(editor,m)=>{editorRef.current=editor;m.editor.setTheme('dojo');editor.addCommand(m.KeyMod.CtrlCmd|m.KeyCode.Enter,()=>runRef.current?.('run'));editor.addCommand(m.KeyMod.CtrlCmd|m.KeyMod.Shift|m.KeyCode.Enter,()=>runRef.current?.('submit'));}} options={{fontSize,fontFamily,minimap:{enabled:false},padding:{top:22},scrollBeyondLastLine:false,automaticLayout:true,tabSize:4,insertSpaces:true,wordWrap:'on',lineNumbersMinChars:3,renderLineHighlight:'all',quickSuggestions:{other:true,comments:false,strings:false},suggestOnTriggerCharacters:true,unicodeHighlight:{ambiguousCharacters:false,nonBasicASCII:false},bracketPairColorization:{enabled:true}}}/></div>
      <div className="editor-status"><span><Check size={12}/>{saveError?'草稿保存失败，请复制备份':'草稿已自动保存'}</span><span>UTF-8<span>4 空格</span>PyTorch</span></div>
      <div className="run-toolbar"><span><Keyboard size={14}/><kbd>Ctrl ↵</kbd> 运行</span><div><button className="secondary" onClick={()=>run('demo')} disabled={busy||!env||!problem}>{busy&&runningMode==='demo'?<LoaderCircle className="spin" size={15}/>:<FileCode2 size={15}/>}运行模板</button><button className="secondary" onClick={()=>run('run')} disabled={busy||!env||!problem}>{busy&&runningMode==='run'?<LoaderCircle className="spin" size={15}/>:<Play size={15}/>}运行样例</button><button className="primary" onClick={()=>run('submit')} disabled={busy||!env||!problem}>{busy&&runningMode==='submit'?<LoaderCircle className="spin" size={15}/>:<Send size={15}/>}提交判题</button></div></div>
      <section className="console"><div className="console-head"><span><Terminal size={15}/>判题结果</span><span>CPU · float64 · 18s 时限</span></div><div className="console-body">{busy?<div className="empty-state running"><LoaderCircle className="spin" size={25}/><h3>正在本地执行 Python</h3><p>{runningMode==='demo'?'执行当前代码的快速运行入口…':'检查输出及本题要求的梯度，请稍候…'}</p></div>:result?<><div className={'result-title '+result.status}>{['accepted','executed'].includes(result.status)?<CheckCheck size={21}/>:<XCircle size={21}/>}<h3>{result.status==='executed'?'模板已运行':result.status==='accepted'?(result.mode==='run'?'样例通过':'全部通过'):result.status==='timeout'?'运行超时':result.status==='error'?'运行错误':'还有用例未通过'}</h3><span>{result.status!=='executed'&&`${result.passed??0} / ${result.total??result.cases.length} 通过 `}{result.ms!=null&&`· ${result.ms} ms`}</span></div>{result.error&&<pre className="error-text">{result.error}</pre>}<div className="case-grid">{result.cases?.map((c,i)=><details key={i} className={c.passed?'case pass':'case fail'}><summary>{c.passed?<Check size={14}/>:<X size={14}/>}<span>{c.name}</span><small>{c.ms} ms</small></summary>{c.error?<pre>{c.error}</pre>:<p>{problem?.inference_only?'数值检查通过':'数值与梯度检查通过'} · 输出 {c.shapes.map(s=>'['+s.join(',')+']').join(', ')}</p>}</details>)}</div>{result.stdout&&<details className="stdout" open><summary>标准输出</summary><pre>{result.stdout}</pre></details>}</>:<div className="empty-state"><div className="terminal-icon"><Terminal size={24}/></div><h3>让代码接受检验</h3><p>运行样例查看结果，准备好后提交完整测试。</p><small>代码在你的本地 Python 环境中执行</small></div>}</div></section>
     </section>
    </div>
   </main>
  </div>
  {showManager&&<BankManager token={env?.token} onClose={()=>setShowManager(false)} onChanged={refreshBank}/>}
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {showReset&&<div className="modal-backdrop" onClick={()=>setShowReset(false)}><div className="modal small" role="dialog" aria-modal="true" aria-label="重置代码" onClick={e=>e.stopPropagation()}><h2>重置当前代码？</h2><p>当前题目的草稿将恢复为初始模板，已提交的历史记录仍可恢复。</p><div className="modal-actions"><button autoFocus className="secondary" onClick={()=>setShowReset(false)}>取消</button><button className="primary" onClick={()=>{updateCode(problem.starter);setShowReset(false);notify('已恢复初始模板')}}>重置代码</button></div></div></div>}
  {showSolution&&<div className="modal-backdrop" onClick={()=>setShowSolution(false)}><div className="modal" role="dialog" aria-modal="true" aria-label="参考实现" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>参考实现</h2><button autoFocus className="icon" aria-label="关闭参考实现" onClick={()=>setShowSolution(false)}><X size={20}/></button></div><p>{problem.title} · 先理解每一步的张量形状，再独立复现。</p><pre>{solution}</pre><div className="modal-actions"><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(solution);notify('参考实现已复制')}catch{notify('复制失败，请手动选择代码')}}}><Copy size={15}/>复制代码</button><button className="primary" onClick={()=>setShowSolution(false)}>继续练习</button></div></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
